version: "3"
services: 
  student-docker-compose:
   # container_name: student-docker-compose
    image: student-docker-compose
    restart: always
    build: .
    ports:
      - 8080:8080 
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
  mysqldb: 
    container_name: mysqldb
    image: mysql:5.6
    volumes:
      -  /home/user/Desktop/db:/var/lib/mysql
    ports: 
     - 3307:3306   
    environment:
      MYSQL_DATABASE: student_db
      MYSQL_ROOT_PASSWORD: root
        